export const SERVER_URL = 'https://findfalcone.herokuapp.com'
export const FETCH_PLANETS_DATA = '/planets'
export const FETCH_VEHICLES_DATA = '/vehicles'
export const FETCH_AUTHENTICATION_TOKEN = '/token'
export const FIND_FALCON = '/find'
